language: node_js
node_js:
  - "node"
branches:
  except:
  - gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_3c0c66028c5c_key -iv $encrypted_3c0c66028c5c_iv
  -in id_rsa.enc -out id_rsa -d
script:
  - webpack
  - node_modules/.bin/gh-pages-travis
env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="id_rsa"
    - GIT_NAME="travis"
    - GIT_EMAIL="deploy@travis-ci.org"
cache: yarn
